apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: sri-aplicacion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        # IMPORTANTE: Reemplaza con tu ID de cuenta de AWS y tu región - Es el ECR donde se encuentra tu imagen
        image: 509333930103.dkr.ecr.us-east-1.amazonaws.com/sri-app-py:de0f05a48bdefcce1d8b6cb40218542495ff7a0b-1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: sri-aplicacion
  annotations:
    # 1. Fuerza a AWS a aprovisionar un Network Load Balancer (NLB) de alto rendimiento
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    
    # 2. EL TRUCO MAESTRO: El tráfico va del NLB directo a las IPs de los Pods (172.31.x.x:8080).
    # Al usar "ip", el puerto 30198 (NodePort) queda completamente anulado y baipaseado.
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    
    # 3. Le indica a AWS que el balanceador debe tener una IP pública accesible desde internet
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer # Esto creará un balanceador de carga en AWS con IP pública
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: python-app