apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: sri-aplicacion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        # IMPORTANTE: Reemplaza con tu ID de cuenta de AWS y tu región - Es el ECR donde se encuentra tu imagen
        image: 469484425805.dkr.ecr.us-east-1.amazonaws.com/sri-app-py:f01ed18a15d909c0c41b6f9c861a7e67453a2ac9
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: sri-aplicacion
spec:
  type: LoadBalancer # Esto creará un balanceador de carga en AWS con IP pública
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: python-app